import assert from 'node:assert/strict'
import { execSync } from 'node:child_process'
const { chromium, devices } = await import(`${execSync('npm root -g', { encoding: 'utf8' }).trim()}/playwright/index.mjs`)
const BASE = process.env.BASE ?? 'http://127.0.0.1:5173'
const browser = await chromium.launch()
try {
  for (const [name, options] of [['desktop', { viewport: { width: 1600, height: 1100 } }], ['phone', { ...devices['iPhone 13'] }], ['tablet', { ...devices['iPad (gen 7)'] }]]) {
    const context = await browser.newContext(options)
    await context.route('**/*', route => new URL(route.request().url()).origin === new URL(BASE).origin ? route.continue() : route.abort())
    const page = await context.newPage(); const errors = []; page.on('pageerror', e => errors.push(e.message))
    await page.goto(BASE); await page.getByRole('heading', { name: 'At the desk.' }).waitFor()
    const original = await page.evaluate(async () => {
      const { db, changed } = await import('/src/lib/db.ts')
      const now = Date.now(), row = (id, body) => ({ id, body, created: now, updated: now, pinned: 0, notebook: 'field-notes' })
      const body = '# Workshop fixture\n\nKeep this original writing.  \n![Original picture](images/details-fixture.png){full}\n\n```md\n#project\nStatus: active\nOwner: code example only\n```\n'
      await db.pages.bulkPut([row('details-fixture', body), row('details-plan', '# Plan fixture\nOriginal plan writing.'), row('details-old-plan', '# Older plan\n#project-plan\nProject: Desk fixture group\nVersion: 2'), row('details-gear', '# Label maker fixture\nOriginal inventory writing.')])
      const blob = new Blob(['synthetic original image bytes'], { type: 'image/png' })
      await db.images.put({ id: 'details-fixture', page: 'details-fixture', blob, type: 'image/png', ext: 'png', added: now })
      changed(); return { body, count: await db.pages.count() }
    })
    const activate = locator => options.hasTouch ? locator.tap() : locator.click()
    const details = page.locator('.desk-details-dialog')
    const row = id => page.evaluate(async id => (await import('/src/lib/db.ts')).db.pages.get(id), id)
    const count = () => page.evaluate(async () => (await import('/src/lib/db.ts')).db.pages.count())
    assert.equal(await page.locator('.desk-project').count(), 0, 'Code examples do not become projects')
    await activate(page.getByRole('button', { name: 'Add project', exact: true }))
    await details.getByLabel('Source page').selectOption('details-fixture')
    await details.getByLabel('Project name / revision group').fill('Desk fixture group')
    await details.getByLabel('Status', { exact: true }).selectOption('active')
    await details.getByLabel('Owner', { exact: true }).fill('Joshua fixture')
    await details.getByLabel('Where we left off', { exact: true }).fill('Chose the material.')
    await details.getByLabel('Next step', { exact: true }).fill('Check the measurements.')
    await activate(details.getByRole('button', { name: 'Save details', exact: true }))
    await details.waitFor({ state: 'detached' })
    await page.locator('.desk-project .desk-next').filter({ hasText: 'Check the measurements.' }).waitFor()
    assert.equal(await count(), original.count)
    assert.ok((await row('details-fixture')).body.startsWith(original.body), 'Other writing, hard break, picture and code retained')
    assert.equal(await page.evaluate(async () => (await (await import('/src/lib/db.ts')).db.images.get('details-fixture')).blob.text()), 'synthetic original image bytes')
    await page.reload(); await page.getByRole('button', { name: 'Edit project details: Workshop fixture' }).waitFor()
    await activate(page.getByRole('button', { name: 'Edit project details: Workshop fixture' }))
    assert.equal(await details.getByLabel('Owner', { exact: true }).inputValue(), 'Joshua fixture')
    await details.getByLabel('Next step', { exact: true }).fill('Unsaved local detail')
    const remote = await page.evaluate(async () => {
      const { db, changed } = await import('/src/lib/db.ts'), p = await db.pages.get('details-fixture')
      const body = `${p.body}\nRemote authored text.`
      await db.pages.put({ ...p, body, updated: p.updated + 1 }); changed(); return body
    })
    await activate(details.getByRole('button', { name: 'Save details', exact: true }))
    await details.getByText(/This page changed while you were editing/).waitFor()
    assert.equal(await details.getByLabel('Next step', { exact: true }).inputValue(), 'Unsaved local detail')
    assert.equal((await row('details-fixture')).body, remote)
    await activate(details.getByRole('button', { name: 'Cancel', exact: true }))
    await activate(page.getByRole('button', { name: 'Add project', exact: true }))
    await details.getByLabel('Page title').fill('New fixture project')
    await details.getByLabel('Next step', { exact: true }).fill('Choose a sketch.')
    await activate(details.getByRole('button', { name: 'Save details', exact: true }))
    await details.waitFor({ state: 'detached' }); assert.equal(await count(), original.count + 1)
    await page.getByRole('button', { name: 'Edit project details: New fixture project' }).waitFor()
    await activate(page.getByRole('button', { name: 'Edit project details: New fixture project' }))
    await details.getByLabel('Status', { exact: true }).selectOption('paused')
    await activate(details.getByRole('button', { name: 'Save details', exact: true }))
    await details.waitFor({ state: 'detached' }); await page.getByRole('button', { name: 'Edit project details: New fixture project' }).waitFor({ state: 'detached' }); assert.equal(await page.locator('.desk-project').count(), 1)
    await activate(page.getByRole('button', { name: 'Add plan', exact: true }))
    await details.getByLabel('Source page').selectOption('details-plan')
    await details.getByLabel('Project name / revision group').fill('Desk fixture group')
    await details.getByLabel('Version', { exact: true }).fill('3')
    await activate(details.getByRole('button', { name: 'Save details', exact: true }))
    await details.waitFor({ state: 'detached' })
    await page.locator('.desk-plan-link').getByText(/Version 3/).waitFor()
    await activate(page.locator('.desk-plan-link summary'))
    await page.locator('.desk-plan-link details').getByRole('button', { name: /^2 ·/ }).waitFor()
    assert.equal(await count(), original.count + 1)
    await page.goto(`${BASE}/workshop`); await page.getByRole('heading', { name: 'Ready to hand.' }).waitFor()
    await activate(page.getByRole('button', { name: 'Add equipment', exact: true }))
    await details.getByLabel('Page title').fill('Cancelled equipment')
    assert.equal(await details.getByRole('button', { name: 'Save details', exact: true }).isEnabled(), false)
    await activate(details.getByRole('button', { name: 'Cancel', exact: true }))
    assert.equal(await count(), original.count + 1)
    await activate(page.getByRole('button', { name: 'Add equipment', exact: true }))
    await details.getByLabel('Source page').selectOption('details-gear')
    await details.getByLabel('I confirm this equipment is owned.', { exact: false }).check()
    await activate(details.getByRole('button', { name: 'Save details', exact: true }))
    await details.waitFor({ state: 'detached' }); await page.locator('.workshop-item').getByText('Label maker fixture').waitFor()
    assert.equal(await page.locator('.workshop-item small').count(), 0)
    await activate(page.getByRole('button', { name: 'Edit equipment details: Label maker fixture' }))
    await details.getByLabel('Brand', { exact: true }).fill('Synthetic brand')
    await activate(details.getByRole('button', { name: 'Save details', exact: true }))
    await details.waitFor({ state: 'detached' }); await page.locator('.workshop-item').getByText('Synthetic brand').waitFor()
    await page.reload(); await page.locator('.workshop-item').getByText('Synthetic brand').waitFor()
    await activate(page.getByRole('button', { name: 'Edit equipment details: Label maker fixture' }))
    await details.getByLabel('I confirm this equipment is owned.', { exact: false }).uncheck()
    await activate(details.getByRole('button', { name: 'Save details', exact: true }))
    await details.waitFor({ state: 'detached' }); await page.locator('.workshop-item').waitFor({ state: 'detached' }); assert.equal(await page.locator('.workshop-item').count(), 0)
    assert.equal((await row('details-gear')).deleted, undefined)
    assert.equal(await count(), original.count + 1)
    assert.deepEqual(errors, [])
    console.log(`PASS ${name}: visible project/plan/equipment forms, atomic saves and reload, content/image preservation, changed-page guard, explicit ownership, grouping and no duplicate notes`)
    await context.close()
  }
} finally { await browser.close() }
