import { useState } from 'react'
import { Card, DeskContainer, Fold, Masthead, Menu, Meta, Paper, Rail, ReadingColumn, RoomTransition, Row, SectionHead, TabBar } from '../components/kit'
import { livePages, daysWritten } from '../lib/db'
import { liveEvents } from '../lib/events'
import { useNotebooks, journalBook } from '../lib/notebooks'
import { allSienaItems } from '../lib/siena-items'
import { clock, dueStamp, lateBy, shortStamp } from '../lib/format'
import { useLive } from '../lib/useLive'
import { titleOf, snippetOf } from '../lib/model'
import { hasAccessDetails } from '../lib/notebook-desk'
import { navigate, to } from '../lib/router'

/* Read actual local data, but preview interactions only change component
   state. Trying a new control must never mark a real reminder complete. */
export default function KitScreen() {
  const books = useNotebooks(), pages = useLive(() => livePages(), [], []), events = useLive(liveEvents, [], []), items = useLive(allSienaItems, [], []), written = useLive(daysWritten, [], new Set<string>())
  const [choice, setChoice] = useState('cream'), [folded, setFolded] = useState(false), [room, setRoom] = useState(0), [notice, setNotice] = useState('Preview controls do not modify saved notes or reminders.')
  const page = pages.find(page => !hasAccessDetails(page.body)), reminder = items.find(item => item.type === 'reminder' && !item.completedAt && !hasAccessDetails(item.body)), event = events[0]
  const title = page ? titleOf(page.body) : 'Your next field note'
  const pageHref = page ? to.page(page.id) : to.overview(), currentBook = books[0]?.id || 'field-notes'
  const actions = ['All notes', 'Remember', 'Export', 'Manage'].map(label => ({ label, onClick: () => setNotice(`${label} selected in preview.`) }))
  return <main className="kit-preview"><DeskContainer>
    <p className="kit-preview-notice">Field Notes · shared kit · development preview. Larger screen redesigns are a later phase.</p>
    <Masthead title="At the desk." dek="Nine familiar parts. Room for what comes next." primary={{ label: 'Back to Field Notes', onClick: () => navigate(to.overview()) }} secondary={actions} />
    <p role="status" className="kit-preview-notice">{notice}</p>
    <section className="kit-demo-section" aria-label="Widths and section headings"><SectionHead eyebrow="01—03 · Structure" title="A place for the writing" count={pages.length} /><ReadingColumn contents={<><a href="#kit-paper">Papers</a><br /><a href="#kit-controls">Rows and controls</a><br /><a href="#kit-navigation">Navigation</a></>}><p>The desk leaves room for a collection; the reading column keeps a longer page comfortable. These components use the same local notes, notebooks, events, and reminders as Field Notes.</p><Meta parts={['Current notebook', books[0]?.name || 'Field Notes', 'Local data']} /></ReadingColumn></section>
    <section id="kit-paper" className="kit-demo-section" aria-label="Paper samples"><SectionHead eyebrow="04 · Surfaces" title="Three papers" /><div className="kit-demo-grid">{(['cream', 'manila', 'plate'] as const).map((stock, index) => <Paper key={stock} stock={stock} rule={(['ruled', 'dot', 'graph'] as const)[index]}><SectionHead title={stock === 'cream' ? 'Cream paper' : stock === 'manila' ? 'Manila stock' : 'Night plate'} count={3} /><p>Ink belongs to its paper. Quiet labels still have something to say.</p><Meta label parts={['Notebook', books[0]?.name || 'Field Notes']} /><Fold label="Paper details" count={2}><p>Readable ink and a shared 28px rhythm.</p></Fold></Paper>)}</div><Paper stock="cream" rule="graph"><Meta parts={['Graph paper', '24px grid']} /></Paper></section>
    <section id="kit-controls" className="kit-demo-section" aria-label="Rows and controls"><SectionHead eyebrow="05 · Rows" title="One row, three uses" /><div className="kit-demo-grid">{(['cream', 'plate'] as const).map(stock => <Paper key={stock} stock={stock}><SectionHead title="Remember" /><Row kind="reminder" title={reminder?.title || reminder?.body || 'Try completing this preview reminder'} meta={reminder?.dueAt ? dueStamp(reminder.dueAt) : 'Today'} late={reminder?.dueAt ? lateBy(reminder.dueAt) : reminder ? undefined : '2 days late'} onToggle={() => setNotice('Preview reminder completed. Saved reminders are unchanged.')} details={<p>{reminder?.body || 'Tap the words to see details. Swipe right on touch to complete this preview row.'}</p>} /><Row kind="event" title={event?.title || 'A little time outside'} time={clock(event?.startTime) || '4 PM'} meta={event?.location || 'Event'} details={<p>{event?.location || 'Event details appear here without leaving the list.'}</p>} /><Row kind="page" title={title} cover={books[0]?.color} meta={page ? shortStamp(page.updated) : 'No note selected'} details={<p>{page ? snippetOf(page.body) : 'Saved notes will appear here when available.'}</p>} /></Paper>)}</div></section>
    <section className="kit-demo-section" aria-label="Card samples"><SectionHead eyebrow="06 · Cards" title="Index, print, and tag" /><div className="kit-demo-grid">{(['index', 'print', 'tag'] as const).map((skin, i) => <Card key={skin} skin={skin} decoration={i} href={pageHref} title={title} body={page ? snippetOf(page.body) : 'Your saved writing supplies the preview. No sample pages are added to the notebook.'} meta={<Meta parts={[books[0]?.name || 'Field Notes', page ? shortStamp(page.updated) : 'Preview']} />} image={skin === 'print' ? { src: '/approved-design/rowan.png', alt: 'Rowan, the Field Notes puffin' } : undefined} onEdit={() => setNotice('Edit control selected. The source page is unchanged.')} notebookColor={books[0]?.color} />)}</div></section>
    <section className="kit-demo-section" aria-label="Menu and fold samples"><SectionHead eyebrow="07—08 · Controls and metadata" title="A menu, a fold, a quiet line" /><Paper stock={choice as 'cream' | 'manila' | 'plate'}><Menu label="Choose paper" value={choice} options={[{ value: 'cream', label: 'Cream', color: '#f6f3ec' }, { value: 'manila', label: 'Manila', color: '#dac891' }, { value: 'plate', label: 'Night plate', color: '#051b1c' }]} onChange={setChoice} /><Fold label="Other notes" count={pages.length}><p>Open with Enter or Space. Escape closes the fold and returns focus.</p><Meta parts={['Visible', choice, pages.length + ' pages']} /></Fold></Paper></section>
    <section id="kit-navigation" className="kit-demo-section" aria-label="Navigation samples"><SectionHead eyebrow="09 · Navigation" title="Between rooms" /><div className="kit-demo-nav"><Rail books={[...books, journalBook()]} selectedNotebook={currentBook} unseen={items.filter(item => !item.seenAt).length} written={written} folded={folded} onFold={() => setFolded(value => !value)} /><div className="kit-demo-nav-main"><button className="kit-primary" onClick={() => setRoom(value => value + 1)}>Preview room transition</button><RoomTransition routeKey={String(room)}><Paper stock="plate"><Masthead child title={room % 2 ? 'A page to return to.' : 'A little room to begin.'} dek="Reduced motion uses a brief fade." /><Meta parts={['Room preview', room + 1]} /></Paper></RoomTransition><TabBar notebook={currentBook} /></div></div></section>
  </DeskContainer></main>
}
